# Generated by Django 5.2.7 on 2025-11-02 19:16

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=contextlib.nullcontext),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=contextlib.nullcontext),
        ),
    ]
